BEGIN TRANSACTION INSERTS
BEGIN TRY
--PERSONA
	INSERT INTO PERSONA(NOMBRES,PRIMER_APELLIDO,SEGUNDO_APELLIDO,CODIGO,ESTADO)
	VALUES('RONALD','PAULINO','ALBERTO','PER1508539',1);

	INSERT INTO PERSONA(NOMBRES,PRIMER_APELLIDO,SEGUNDO_APELLIDO,CODIGO,ESTADO)
	VALUES('ALEXANDER','ALMONTE','TINEO','PER2098250',1);

	INSERT INTO PERSONA(NOMBRES, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CODIGO, ESTADO)
	VALUES('WILLY CARLOS', 'PORTALATIN', 'OWEN','PER5845931',1);


--EMPRESA
	INSERT INTO EMPRESA(DESCRIPCION,CODIGO,ESTADO)VALUES('ABONAP','EMPABO00001',1);


--SUCURSAL
	INSERT INTO SUCURSAL(DESCRIPCION,CODIGO,ESTADO,ID_EMPRESA)VALUES('AVENIDA LIBERTAD', 'SUC00001', 1,1);
	INSERT INTO SUCURSAL(DESCRIPCION,CODIGO,ESTADO,ID_EMPRESA)VALUES('16 DE AGOSTO', 'SUC00002 ', 1,1);
	INSERT INTO SUCURSAL(DESCRIPCION,CODIGO,ESTADO,ID_EMPRESA)VALUES('SANTO DOMINGO ', 'SUC00009 ', 1,1);


--TIPO DOCUMENTO
	INSERT INTO TIPO_DOCUMENTO(DESCRIPCION,CODIGO)VALUES('RNC',1);
	INSERT INTO TIPO_DOCUMENTO(DESCRIPCION,CODIGO)VALUES('CEDULA',2);
	INSERT INTO TIPO_DOCUMENTO(DESCRIPCION,CODIGO)VALUES('PASAPORTE',3);


--DOCUMENTO
	INSERT INTO DOCUMENTO(DESCRIPCION,ESTADO,ID_TIPO_DOCUMENTO)VALUES('402-7896247-3',1,2);
	INSERT INTO DOCUMENTO(DESCRIPCION,ESTADO,ID_TIPO_DOCUMENTO)VALUES('048-0089654-4',1,2);
    INSERT INTO DOCUMENTO(DESCRIPCION,ESTADO,ID_TIPO_DOCUMENTO)VALUES('047-98745960',1,2);
	INSERT INTO DOCUMENTO(DESCRIPCION,ESTADO,ID_TIPO_DOCUMENTO)VALUES('005-87598-9',0,1);


--EMPLEADO
	INSERT INTO EMPLEADO(CODIGO, ESTADO,ID_PERSONA,ID_SUCURSAL)VALUES('EMP00001',1,1,1);
	INSERT INTO EMPLEADO(CODIGO, ESTADO,ID_PERSONA,ID_SUCURSAL)VALUES('EMP00002',1,2,1);


--CLIENTE
	INSERT INTO CLIENTE(CODIGO, ESTADO,ID_PERSONA,ID_SUCURSAL)VALUES('CLI00001',1,1,1);
	INSERT INTO CLIENTE(CODIGO, ESTADO,ID_PERSONA,ID_SUCURSAL)VALUES('CLI00002',1,2,1);


--PRESTAMO
	INSERT INTO PRESTAMO(CODIGO,ESTADO,ID_CLIENTE,ID_SUCURSAL,MONTO)VALUES('PRES00001','C',1,1,30000.2);
	INSERT INTO PRESTAMO(CODIGO,ESTADO,ID_CLIENTE,ID_SUCURSAL,MONTO)VALUES('PRES00002','A',1,2,25000.1);
	INSERT INTO PRESTAMO(CODIGO,ESTADO,ID_CLIENTE,ID_SUCURSAL,MONTO)VALUES('PRES00003','A',2,3,12000.5);

	COMMIT TRAN INSERTS;
END TRY
BEGIN CATCH 
	ROLLBACK TRAN INSERTS;
END CATCH;


--DELETE FROM PERSONA;
--DELETE FROM EMPRESA;
--DELETE FROM SUCURSAL;
--DELETE FROM TIPO_DOCUMENTO;
--DELETE FROM DOCUMENTO;
--DELETE FROM EMPLEADO;
--DELETE FROM CLIENTE;
--DELETE FROM PRESTAMO;

--SELECT * FROM PERSONA;
--SELECT * FROM EMPRESA;
--SELECT * FROM SUCURSAL;
--SELECT * FROM TIPO_DOCUMENTO;
--SELECT * FROM DOCUMENTO;
--SELECT * FROM EMPLEADO;
--SELECT * FROM CLIENTE;
--SELECT * FROM PRESTAMO;