CREATE TABLE DEPARTAMENTO
(
	ID_DEPARTAMENTO INT IDENTITY(1,1),
	DESCRIPCION VARCHAR(45),
	FECHA_CREACION DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	CODIGO VARCHAR(30),
	ESTADO BIT,
	ID_SUCURSAL INT
);

CREATE TABLE EMPRESA
(
	ID_EMPRESA INT IDENTITY(1,1),
	DESCRIPCION VARCHAR(45),
	FECHA_CREACION DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	CODIGO VARCHAR(30),
	ESTADO BIT
);

CREATE TABLE PERSONA
(
	ID_PERSONA INT IDENTITY(1,1),
	NOMBRES VARCHAR(100),
	PRIMER_APELLIDO VARCHAR(100),
	SEGUNDO_APELLIDO VARCHAR(100),
	FECHA_CREACION DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	CODIGO VARCHAR(30),
	ESTADO BIT
);

CREATE TABLE DOCUMENTO
(
	ID_DOCUMENTO INT IDENTITY(1,1),
	FECHA_CREACION DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	DESCRIPCION VARCHAR(50),
	ESTADO BIT,
	ID_TIPO_DOCUMENTO INT
);

CREATE TABLE TIPO_DOCUMENTO
(
	ID_TIPO_DOCUMENTO INT IDENTITY(1,1),
	DESCRIPCION VARCHAR(50),
	CODIGO VARCHAR(30)
);

CREATE TABLE SUCURSAL
(
	ID_SUCURSAL INT IDENTITY(1,1),
	DESCRIPCION VARCHAR(50),
	FECHA_CREACION DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	CODIGO VARCHAR(30),
	ESTADO BIT,
	ID_EMPRESA INT
);

CREATE TABLE EMPLEADO
(
	ID_EMPLEADO INT IDENTITY(1,1),
	FECHA_CREACION DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	CODIGO VARCHAR(30),
	ESTADO BIT,
	ID_PERSONA INT,
	ID_SUCURSAL INT
);

CREATE TABLE CLIENTE
(
	ID_CLIENTE INT IDENTITY(1,1),
	FECHA_CREACION DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	CODIGO VARCHAR(30),
	ESTADO BIT,
	ID_PERSONA INT,
	ID_SUCURSAL INT
);

CREATE TABLE PRESTAMO
(
	ID_PRESTAMO INT IDENTITY(1,1),
	FECHA_CREACION DATETIME,
	FECHA_ACTUALIZACION DATETIME,
	CODIGO VARCHAR(30),
	ID_CLIENTE INT,
	ID_SUCURSAL INT,
	ESTADO VARCHAR(25),
	MONTO DECIMAL(8,2)
);

DROP TABLE DEPARTAMENTO;
DROP TABLE DOCUMENTO;
DROP TABLE TIPO_DOCUMENTO;
DROP TABLE EMPLEADO;
DROP TABLE PRESTAMO;
DROP TABLE SUCURSAL;
DROP TABLE CLIENTE;
DROP TABLE EMPRESA;
DROP TABLE PERSONA;

